config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd' # routes for devise modules on User
  resources :users # custom admin-type CRUD for users

  root to: 'home#index'

  get '/users', to: 'users#index'

  resources :dogs do
    resources :comments
    resources :images
  end

  resources :donations do
    resources :charges, :only => [:create]
  end

  resources :testimonials

  resources :applicants, :only => [:index, :new, :create, :show, :destroy]

  resources :training, :only => [:index]

  resources :faq, :only => [:index]

  resources :about, :only => [:index]

  resources :home, :only => [:index]
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :images, dependent: :destroy
  validates :name, presence: true
  validates :sex, presence: true
  validates :age, presence: true
  validates :info, presence: true
  validates :breed, presence: true
  has_attached_file :image, styles: {
    standard: '750x500',
    profile: '450x300',
    thumb: '300x225'
   }

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all.order(created_at: :desc)
  end

  def new
    @dog = Dog.new
    render :new
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to  dogs_path
    else
      render :new
    end
  end

  def show
    @dog = Dog.find(params[:id])
    @images = @dog.images
    @comments = @dog.comments
    render :show
  end

  def edit
    @dog = Dog.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    redirect_to dog_path(@dog)
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :sex, :age, :breed, :info, :image, :user_id)
  end

  def find_dog
    @dog = Dog.find(params[:id])
  end
end

app/views/dogs/_form.html.erb
<div id="forms">
  <header>Add New Rescue Dog</header>
  <br>
  <%= form_for @dog, html: { multipart: true }, remote: true do |f| %>
    <div>
      <%= f.label :name %>
      <br>
      <%= f.text_field :name, required: 'required' %>
      <br><br>
      <%= f.label :breed %>
      <br>
      <%= f.text_field :breed, required: 'required' %>
      <br><br>
      <%= f.label :age %>
      <br>
      <%= f.text_field :age, required: 'required' %>
      <br><br>
      <%= f.label :sex %>
      <br>
      <%= f.text_field :sex, required: 'required' %>
      <br><br>
      <%= f.label :info %>
      <br>
      <%= f.cktext_area :info, required: 'required' %>
      <br><br>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
    <br>
    <div class='form-group'>
      <%= f.submit class: 'btn btn-success btn-md' %>
    </div>
    <%= link_to "Return to Available Dogs", dogs_path, class: "btn btn-primary btn-md" %>
    <br>
  <% end %>
</div>

app/views/dogs/edit.html.erb
<div class="universal-page">
  <% if current_user %>
    <%= render 'form' %>
  <% end %>
</div>

app/views/dogs/edit.js.erb
$('#edit-dog-link').hide()
$('#edit-dog-form').html('<%= j render "form" %>')

app/views/dogs/index.html.erb
<div class="universal-page">
  <%= image_tag("https://s3-us-west-2.amazonaws.com/vondubinhaus/general/images/rescue.png", id: "pic") %>
  <div class="universal-page-text" id="dog-index-text">
    <div id="header-text">
      Rescue
    </div>
    <br>
    German Shepherds are our specialty, our passion, and protecting the breed and their integrity is our priority.
    We strive to make sure German Shepherd dogs that are no longer wanted can be
    rescued and do not end up at the pound or worse. We typically only accept purebred
    German Shepherds that can no longer be cared for due to life changes or that other rescues have
    turned away due to their behavioral problems.
    We want to ensure these dogs get a second chance, and enjoy the challenge of rehabilitating them if need be.
    <br><br>
    We may accept other breeds depending on the situation as well. Please call to see if your dog, or one
    you know of might be a good candidate for our services. That said, our first objective is always
    to keep them with you and focus on training, but circumstances often tend to prevail.
    <br><br>
    If you're interested in one of our current available rescues, please submit an adoption form, which
    can be found on each individual animals adoption page. All dog showings are by appointment only. Once
    your application has been reviewed, you will be contacted shortly. Re-homing fees varies from dog to dog depending on: food, training and if there are
    any vet bills. All rescues from Von Dubinhaus Shepherds come with lifetime training
    included as part of their adoption.
    <br><br>
    If you know of a German Shepherd Dog in need of re-homing, please contact Brandon at: <a href="mailto:brandonseroyer@gmail.com">brandonseroyer@gmail.com</a>
    or (503) 806-2572.
  </div>
  <br>
  <center><header>Available for Adoption</header></center>
  <br>
  <center>
  <div id="dog-row" class="row">
    <% @dogs.each do |dog| %>
    <div class="col-md-4">
      <%= link_to dog_path(dog) do %>
      <span id="dog-box" class="profile-div">
        <br>
        <%= image_tag(dog.image.url) %>
        <br><br>
        <p id="dog-box-title">Click to learn about <%= dog.name %></p>
        <br>
      </span>
      <% end %>
      <br><br>
    </div>
    <% end %>
  </div>
  </center>
  <br>
</div>

app/views/dogs/new.html.erb
<div class="universal-page">
  <% if current_user %>
    <div id="forms">
      <div class="forms">
        <%= render 'form' %>
      </div>
    </div>
  <% end %>
  <br>
</div>

app/views/dogs/show.html.erb
<div id="profile-page">
  <center>
  <div id="profile-box">
    <div id="profile-head">
      <div id="donate-social">
        <div id="donate">
          <%= link_to 'Donate', new_donation_path, id:'text-color2' %>
        </div>
        <br><br>
        <div id="social">
          <div id="text-color2">
            Help <%= @dog.name %> get adopted!
          </div>
          <%= social_share_button_tag(@dog.name,'data-twitter-title' => "Need a friend?
          Check out this awesome rescue dog looking for a home!", :popup => "true",) %>
        </div>
        <br><br>
      </div>
      <%= @dog.name %>
    </div>
  <div id="profile-pic-stats">
    <%= image_tag @dog.image.url(:profile), id: 'pic' %>
    <br>
    <% if current_user %>
    <%= link_to "Add Photo", new_dog_image_path(@dog) %>
    <% end %>
    <% if @dog.images.any? %>
    <div class="well" style="max-width:405px;">
      <% @images.each do |image| %>
      <div class="img-thumbnail">
        <%= link_to image_tag(image.avatar.url(:thumb)), image.avatar.url(:original), data: { toggle: "lightbox"} %>
      </div>
        <% if current_user %>
        <%= link_to "Delete", dog_image_path(@dog, image),
        :data => {:confirm => "You sure?",
          :method => "delete"} %>
        <% end %>
      <% end %>
      </div>
    <% end %>
    <div id="apply-dog">
    <%= link_to "Apply for Adoption", new_applicant_path, class: "btn btn-primary btn-lg" %>
    </div>
    <div id="dog-stats">
      <%= @dog.breed %>
      <br>
      <%= @dog.age %> years old
      <br>
      <%= @dog.sex %>
    </div>
  </div>
  <hr id="dog-hr">
  <div id="dog-story">
    <h1><%= @dog.name %>'s Story</h1>
    <p><%= simple_format(@dog.info) %></p>
  </div>
  <hr id="dog-hr">
  <div id="dog-comments">
    <h2>Questions & Comments</h2>
    <% if @dog.comments.any? %>
      <% @comments.each do |comment| %>
        <ul>
        <b><%= comment.name %></b>: <h4><%= comment.comment %></h4>
        <% if current_user %>
          <%= link_to "Edit", edit_dog_comment_path(@dog, comment), id: 'edit-comment' %> |
          <%= link_to "Delete", dog_comment_path(@dog, comment), id: 'delete-comment',
          :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
        <% end %>
        </ul>
      <% end %>
    <% else %>
      <p>There are no comments yet!</p>
    <% end %>
    <%= link_to "Add a comment", new_dog_comment_path(@dog), class: "btn btn-primary btn-md" %>
  </div>
  <% if current_user %>
    <div id='edit-dog-form'>
    </div>
    <hr>
    <div id='dog-links'>
    <p>
    <%= link_to "Edit", edit_dog_path(@dog), id:'edit-dog-link', remote: true %><br>
    <%= link_to "Delete", dog_path(@dog),
    :data => {:confirm => "You sure?",
      :method => "delete"} %><br>
    </div>
  <% end %>
  <%= link_to "Return to Available Dogs", dogs_path, class: "btn btn-primary btn-lg" %></p>
  </div>
  </center>
</div>