config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'd' # routes for devise modules on User
  resources :users # custom admin-type CRUD for users

  root to: 'home#index'

  get '/users', to: 'users#index'

  resources :dogs do
    resources :comments
    resources :images
  end

  resources :donations do
    resources :charges, :only => [:create]
  end

  resources :testimonials

  resources :applicants, :only => [:index, :new, :create, :show, :destroy]

  resources :training, :only => [:index]

  resources :faq, :only => [:index]

  resources :about, :only => [:index]

  resources :home, :only => [:index]
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :amount, presence: true
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  def index
    @donations = Donation.order(created_at: :desc).page(params[:page]).per(5)
  end

  def new
    @donation = Donation.new
    render :new
  end

  def create
    @donation = Donation.new(donation_params)
    @donation = clean_dollars
    @donation = Donation.new(donation_params)
    if verify_recaptcha
      @donation.save
      UserMailer.donation_email.deliver
      render :show
    else
      render :new
    end
  end

  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy
    redirect_to donations_path
  end

  private

  def donation_params
    params.require(:donation).permit(:first_name, :last_name, :email, :amount, :message)
  end

  def clean_dollars
    params[:donation][:amount] = params[:donation][:amount].gsub("$","")
  end
end

app/views/donations/_form.html.erb
<div id="forms">
  <header>Make a Donation</header>
  <br>
  <%= form_for @donation do |f| %>
    <%= f.label :first_name %>
    <br>
    <%= f.text_field :first_name, required: 'required' %>
    <br><br>
    <%= f.label :last_name %>
    <br>
    <%= f.text_field :last_name, required: 'required' %>
    <br><br>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email, required: 'required' %>
    <br><br>
    <b>Donation</b> <%= f.label :amount %>
    <br>
    <%= f.text_field :amount, required: 'required' %>
    <br><br>
    <%= f.label :message %> (optional)
    <br>
    <%= f.text_area :message %>
    <br><br>
    <%= recaptcha_tags %>
    <br>
    <%= f.submit "Submit Donation", class: 'btn btn-primary btn-lg' %>
  <% end %>
</div>

app/views/donations/index.html.erb
<div class="universal-page">
  <% if current_user %>
    <div id="forms">
      <header>Donation Index</header>
      <% @donations.each do |donation| %>
        <br>
        Date: <%= donation.created_at %><br><br>
        Name: <%= donation.first_name %> <%= donation.last_name %><br>
        Email: <%= donation.email %><br>
        Donation: $<%= donation.amount %><br>
        Message: <%= donation.message %>
        <p><%= link_to "Delete", donation_path(donation),
        :data => {:confirm => "You sure?",
          :method => "delete"} %></p>
        <hr>
      <% end %>
      <%= paginate @donations %>
    </div>
  <% end %>
</div>

app/views/donations/new.html.erb
<div class="universal-page">
  <%= image_tag("https://s3-us-west-2.amazonaws.com/vondubinhaus/general/images/gsd-lay.png", id: "pic") %>
  <div class="universal-page-text" id="donate-text">
   <div id="header-text">
     Donate
   </div>
  <br>
  Von Dubinhaus Shepherds Rescue is funded completely out of pocket. Donations
  of any amount gifted to our organization are greatly appreciated as it allows us to
  continue to do what we love so much -- help German Shepherd Dogs in need!
  <br><br>
  Aside from cash donation we also accept dog food, travel kennels, kennel panels,
  fencing, blankets or paving stones for kennel flooring, toys and treats. Our rescue dogs and their
  future owners will be very grateful for any contributions to help the
  rescue -- it truly makes a massive difference!
  </div>
  <div id="forms">
    <div class="forms">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/donations/show.html.erb
<div class="universal-page">
  <div id="forms">
    <div class="donation-pages">
      <header>Payment Confirmation</header>
      <%= @donation.first_name %>, you have selected a donation amount of $<%= number_to_currency(@donation.amount) %>
      <%= form_tag donation_charges_path(@donation) do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
      </article>
      <br>
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description= "$<%= @donation.amount %>"
              data-amount="<% @donation.amount %>"
              data-locale="auto"></script>
      <% end %>
    </div>
    <br>
    <%= link_to "Cancel Payment, Return to Donation Page", new_donation_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>